### ISSUE TITLE
jQuery

### ISSUE THREAD

**Issue by michaelspellacy** [tmpworldwide/tb-sa-plugins#1]
Don't forget, you may be able to remove jQuery, since it is already running in the environment the plugin will exist in. Slip that baby down! :-P

**Comment by jorgefelico** [comment]
I'll have to look into it some more. I've been reading and it says that the extension runs in a "sandboxed" mode which doesn't let us access any of the in-page scripts. HOWEVER, I was able to overcome this by injecting JS into the page when adding the Emmet plugin feature to the editor. Just takes a bit more tinkering...

**Comment by michaelspellacy** [comment]
Ah, I see. Okay then. :-)

**Comment by Brockenstein** [comment]
Closing issues because I have confirmed that the chrome script can not utilize the jquery running on the page.
